### ISSUE TITLE
Add verbose output as an overall pipeline config parameter

### ISSUE THREAD

**Issue by rachel3834** [mpgh/pyDANDIA#5]
Set the 'verbose' from the overall pipeline config.json file.  All stages should respect this parameter.

**Comment by rachel3834** [comment]
I've added verbose to the config.json file. 

I've updated stage 0 to respect this parameter throughout in its logging output.  
Next step is to do the same updates to stage 1

**Comment by rachel3834** [comment]
@ytsapras I'm now looking at stage 1 and I see you have implemented a 'verbosity' parameter with various levels of output, including to screen.  I considered implementing this through-out the pipeline since I can see some cases where it would be useful, but I hit an issue: this could cause a problem when pipeline_control is called in parallelized mode.  

In that mode, it spawns multiple instances of reduction_control which are independent processes.  If this is run from the command line, then it will send the printed output to the terminal window of ALL of the processes simultaneously.  If its run under the cron, it will break the code - it can stop it running, depending on the $SHELL set up.  

For this reason, output printed to the shell is always a worry in a pipeline: it makes it easy for users to configure it in such a way that it breaks or produces non-sensical output.  

I then considered implementing verbosity, but automatically deactivating printed output to screen if its being run in parallel mode, but there is no easy or clean way for the software to know whether its being run from the command line versus under the cron.  

So my take-away from all this is that verbosity may be quite difficult to implement in a robust way.  

At this point, I'm working on a model where 
verbose=0 = minimal output to log file
verbose=1 = extra output to log file
...but no screen output.  If you switch on the verbose output (e.g. for testing) then you can of course  read the output in the log.  

What do you think?  Does this model work for you?

**Comment by ytsapras** [comment]
I would prefer to see output on the shell during development and it would be very useful for first time users as well. In verbosity is set to 0 (no shell output, only in logs), which will be the default, would that create a problem when running it as a cron job or in parallel instances? Alternatively we can suggest to users keeping the relevant log files open on an editor window or browser and keep refreshing to see the updated output.

**Comment by rachel3834** [comment]
OK, to have the convenience of the option of screen output, I decided to implement the full verbosity = {0,1,2} option, but as a pipeline setup parameter rather than as a config.json parameter.  

The reason to make it a setup parameter is to avoid the chicken-and-egg problem of having to start the pipeline, then read the verbosity from the config.json, and possibly end up with different values for the setting.  

Verbosity can now be set as a commandline option to reduction_control.py using the -v flag.
