### ISSUE TITLE
running a test reduction 

### ISSUE THREAD

**Issue by mpgh** [mpgh/pyDANDIA#8]
after calling reduction_control for the test dataset, stage0 does not create any metadata file. The logs report the following (side remark "[MYPATH]" was correctly set....)

2017-10-12T10:28:23 Read pipeline configuration from /[MYPATH]/pyDANDIA/pyDANDIA/tests/data/proc/ROME-FIELD-0002_lsc-doma-1m0-05-fl15_ip/../configs/config.json
2017-10-12T10:28:23 No metadata created or loaded : check this!

**Comment by mpgh** [comment]
Trying to trace it a bit further leads to the following, which seems to be an issue, which does not appear on older packages (btw, I have a copy of the expected metadata fitsfile, so I can continue for the time being)

create_or_load_the_reduction_metadata(output_metadata_directory, metadata_name, verbose, log)
     19             reduction_metadata = metadata.MetaData()
     20 
---> 21             reduction_metadata.create_metadata_file(output_metadata_directory, metadata_name)
     22 
     23             if verbose == True and log != None:

 in create_metadata_file(self, metadata_directory, metadata_name)
     71         self.create_data_inventory_layer()
     72 
---> 73         tbhdu1 = fits.BinTableHDU(self.data_architecture[1], header=self.data_architecture[0])
     74         tbhdu2 = fits.BinTableHDU(self.data_inventory[1], header=self.data_inventory[0])
     75 

/work/Titania/anaconda2/lib/python2.7/site-packages/astropy/io/fits/hdu/table.pyc in __init__(self, data, header, name, uint)
    369                 pass
    370             else:
--> 371                 raise TypeError('Table data has incorrect type.')
    372 
    373         if not (isinstance(self._header[0], string_types) and

TypeError: Table data has incorrect type.

**Comment by rachel3834** [comment]
Can you quote the version of astropy you are using?

**Comment by mpgh** [comment]
astropy.__version__
1.3.3

**Comment by mpgh** [comment]
The same applies to astropy version 1.3.3

**Comment by rachel3834** [comment]
I recommend that you try astropy=v2.0 which is what I'm running.
